Fixed error in config
I'm an idiot. This error should be solved.
/home/ubuntu/workspace/config.js:83
        'edgejs': true, 
        ^^^^^^^^

SyntaxError: Unexpected string
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/index.js:62:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)